"""update Permissions and PermissionRoleAssociation

Revision ID: 928c205c047c
Revises: 7b593999f0ee
Create Date: 2025-08-05 21:39:19.906022

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "928c205c047c"
down_revision: Union[str, Sequence[str], None] = "7b593999f0ee"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
