"""add Permissions and association_role_permission_table

Revision ID: 7b593999f0ee
Revises: aba53afadf77
Create Date: 2025-08-05 20:18:37.077833

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7b593999f0ee"
down_revision: Union[str, Sequence[str], None] = "aba53afadf77"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "permissions",
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "permission_role_association_table",
        sa.Column("permission_id", sa.Integer(), nullable=False),
        sa.Column("role_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["permission_id"],
            ["permissions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["roles.id"],
        ),
        sa.PrimaryKeyConstraint("permission_id", "role_id", "id"),
    )
    op.alter_column(
        "roles", "name", existing_type=sa.VARCHAR(length=255), nullable=False
    )
    op.create_unique_constraint(None, "roles", ["name"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "roles", type_="unique")
    op.alter_column(
        "roles", "name", existing_type=sa.VARCHAR(length=255), nullable=True
    )
    op.drop_table("permission_role_association_table")
    op.drop_table("permissions")
    # ### end Alembic commands ###
